package healthtech.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ReminderTypeEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ReminderTypeEnum() {
    super(0x302f6a2f71494d75L, 0x8daf01fecbeaf5d3L, 0x6c0fdc58b27e8d27L, "ReminderTypeEnum", "r:f9a5d9b0-e4d1-425f-bdda-6234399d7263(healthtech.structure)/7786684554256747815");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_WEEKLY_0 = new EnumerationDescriptor.MemberDescriptor("WEEKLY", "every week", 0x6c0fdc58b27e8d28L, "r:f9a5d9b0-e4d1-425f-bdda-6234399d7263(healthtech.structure)/7786684554256747816");
  private final EnumerationDescriptor.MemberDescriptor myMember_YEARLY_0 = new EnumerationDescriptor.MemberDescriptor("YEARLY", "every year", 0x6c0fdc58b27e8d29L, "r:f9a5d9b0-e4d1-425f-bdda-6234399d7263(healthtech.structure)/7786684554256747817");
  private final EnumerationDescriptor.MemberDescriptor myMember_DAILY_0 = new EnumerationDescriptor.MemberDescriptor("DAILY", "every day", 0x6c0fdc58b27e8d2cL, "r:f9a5d9b0-e4d1-425f-bdda-6234399d7263(healthtech.structure)/7786684554256747820");
  private final EnumerationDescriptor.MemberDescriptor myMember_MONTHLY_0 = new EnumerationDescriptor.MemberDescriptor("MONTHLY", "every month", 0x6c0fdc58b27e8d30L, "r:f9a5d9b0-e4d1-425f-bdda-6234399d7263(healthtech.structure)/7786684554256747824");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x302f6a2f71494d75L, 0x8daf01fecbeaf5d3L, 0x6c0fdc58b27e8d27L, 0x6c0fdc58b27e8d28L, 0x6c0fdc58b27e8d29L, 0x6c0fdc58b27e8d2cL, 0x6c0fdc58b27e8d30L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_WEEKLY_0, myMember_YEARLY_0, myMember_DAILY_0, myMember_MONTHLY_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "WEEKLY":
        return myMember_WEEKLY_0;
      case "YEARLY":
        return myMember_YEARLY_0;
      case "DAILY":
        return myMember_DAILY_0;
      case "MONTHLY":
        return myMember_MONTHLY_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
