package healthtech.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_MeasurementUnit extends EnumerationDescriptorBase {

  public EnumerationDescriptor_MeasurementUnit() {
    super(0x302f6a2f71494d75L, 0x8daf01fecbeaf5d3L, 0xbb4c0906ddb7bfL, "MeasurementUnit", "r:f9a5d9b0-e4d1-425f-bdda-6234399d7263(healthtech.structure)/52719422298503103");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_KILOGRAM_0 = new EnumerationDescriptor.MemberDescriptor("KILOGRAM", "kg", 0xbb4c0906ddb7c0L, "r:f9a5d9b0-e4d1-425f-bdda-6234399d7263(healthtech.structure)/52719422298503104");
  private final EnumerationDescriptor.MemberDescriptor myMember_CELSIUS_DEGREE_0 = new EnumerationDescriptor.MemberDescriptor("CELSIUS_DEGREE", "°C", 0xbb4c0906ddcf21L, "r:f9a5d9b0-e4d1-425f-bdda-6234399d7263(healthtech.structure)/52719422298509089");
  private final EnumerationDescriptor.MemberDescriptor myMember_BEATS_PER_MINUTE_0 = new EnumerationDescriptor.MemberDescriptor("BEATS_PER_MINUTE", "bpm", 0xbb4c0906ddcf24L, "r:f9a5d9b0-e4d1-425f-bdda-6234399d7263(healthtech.structure)/52719422298509092");
  private final EnumerationDescriptor.MemberDescriptor myMember_MERCURY_MM_0 = new EnumerationDescriptor.MemberDescriptor("MERCURY_MM", "mmHG", 0xbb4c0906ddcf28L, "r:f9a5d9b0-e4d1-425f-bdda-6234399d7263(healthtech.structure)/52719422298509096");
  private final EnumerationDescriptor.MemberDescriptor myMember_MOL_PER_LITRE_0 = new EnumerationDescriptor.MemberDescriptor("MOL_PER_LITRE", "mmol/L", 0xbb4c0906ddd1bdL, "r:f9a5d9b0-e4d1-425f-bdda-6234399d7263(healthtech.structure)/52719422298509757");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x302f6a2f71494d75L, 0x8daf01fecbeaf5d3L, 0xbb4c0906ddb7bfL, 0xbb4c0906ddb7c0L, 0xbb4c0906ddcf21L, 0xbb4c0906ddcf24L, 0xbb4c0906ddcf28L, 0xbb4c0906ddd1bdL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_KILOGRAM_0, myMember_CELSIUS_DEGREE_0, myMember_BEATS_PER_MINUTE_0, myMember_MERCURY_MM_0, myMember_MOL_PER_LITRE_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "KILOGRAM":
        return myMember_KILOGRAM_0;
      case "CELSIUS_DEGREE":
        return myMember_CELSIUS_DEGREE_0;
      case "BEATS_PER_MINUTE":
        return myMember_BEATS_PER_MINUTE_0;
      case "MERCURY_MM":
        return myMember_MERCURY_MM_0;
      case "MOL_PER_LITRE":
        return myMember_MOL_PER_LITRE_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
