package healthtech.actions;

/*Generated by MPS */

import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import jetbrains.mps.smodel.action.SNodeFactoryOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class createDefaultUnitConfigBeforeProtocol {
  public static class NodeFactory_52719422299948138 implements NodeFactory {
    public void setup(SNode newNode, SNode sampleNode, SNode enclosingNode, SModel model) {
      if (ListSequence.fromList(SModelOperations.roots(model, CONCEPTS.MeasurementUnitConfig$RG)).isEmpty()) {
        SNodeFactoryOperations.createNewRootNode(model, CONCEPTS.MeasurementUnitConfig$RG, null);
      }

    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept MeasurementUnitConfig$RG = MetaAdapterFactory.getConcept(0x302f6a2f71494d75L, 0x8daf01fecbeaf5d3L, 0xbb4c0906ddd1c3L, "healthtech.structure.MeasurementUnitConfig");
  }
}
