package com.boyarsky.lang.runtime.impl;

/*Generated by MPS */


public class InputSpec {
  private Integer timeRange;
  private Integer size;
  private MType type;


  public InputSpec(Integer timeRange, Integer size, MType type) {
    this.timeRange = timeRange;
    this.size = size;
    this.type = type;
  }

  public Integer getTimeRange() {
    return this.timeRange;
  }
  public void setTimeRange(Integer timeRange) {
    this.timeRange = timeRange;
  }
  public Integer getSize() {
    return this.size;
  }
  public void setSize(Integer size) {
    this.size = size;
  }
  public MType getType() {
    return this.type;
  }
  public void setType(MType type) {
    this.type = type;
  }
}
