package com.boyarsky.lang.runtime.impl;

/*Generated by MPS */

import com.boyarsky.lang.runtime.Range;
import com.boyarsky.lang.runtime.utils.MeasurementUtils;

public class NonLimitedRange extends Range {
  private Float operand;

  @Override
  public boolean checkRange(Measurement m) {
    boolean res = false;
    Float value = (getType() == MType.DIASTOLIC ? MeasurementUtils.getDiastolic(m) : (getType() == MType.SYSTOLIC ? MeasurementUtils.getSystolic(m) : Float.valueOf(m.getValue())));
    if (getOperator().equals("<=")) {
      return value <= operand;
    }
    if (getOperator().equals(">=")) {
      return value >= operand;
    }
    if (getOperator().equals(">")) {
      return value > operand;
    }
    if (getOperator().equals("<")) {
      return value < operand;
    }
    return res;
  }

  public Float getOperand() {
    return this.operand;
  }
  public void setOperand(Float operand) {
    this.operand = operand;
  }

}
