package healthtech.sandbox;

/*Generated by MPS */


public class BinaryRange extends Range {
  private Float operand;
  private Float secondOperand;

  public Float getOperand() {
    return this.operand;
  }
  public void setOperand(Float operand) {
    this.operand = operand;
  }
  public Float getSecondOperand() {
    return this.secondOperand;
  }
  public void setSecondOperand(Float secondOperand) {
    this.secondOperand = secondOperand;
  }
}
