package healthtech.sandbox;

/*Generated by MPS */

import java.util.List;

public class EvaluationEntry {
  private List<Range> ranges;
  private OutputResult result;

  public List<Range> getRanges() {
    return this.ranges;
  }
  public void setRanges(List<Range> ranges) {
    this.ranges = ranges;
  }
  public OutputResult getResult() {
    return this.result;
  }
  public void setResult(OutputResult result) {
    this.result = result;
  }
}
