package healthtech.sandbox;

/*Generated by MPS */

import java.util.List;
import java.util.ArrayList;

public class hypertension implements IProtocol {
  private String name = "hypertension";
  private String description = "Hypertension is a desease with blood pressure more than 140/90";
  private String reference = "https://guidelines.moz.gov.ua/documents/2988";
  private List<InputSpec> inputSpecs = new ArrayList<InputSpec>();

  public hypertension() {
    InputSpec inputSpec_sdvlmb_a = new InputSpec(2, 1, MType.PULSE);
    inputSpecs.add(inputSpec_sdvlmb_a);
  }

  @Override
  public void evaluate(List<Measurement> measurements) {

  }


  public String getName() {
    return this.name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public String getDescription() {
    return this.description;
  }
  public void setDescription(String description) {
    this.description = description;
  }
  public String getReference() {
    return this.reference;
  }
  public void setReference(String reference) {
    this.reference = reference;
  }
  public List<InputSpec> getInputSpecs() {
    return this.inputSpecs;
  }
  public void setInputSpecs(List<InputSpec> inputSpecs) {
    this.inputSpecs = inputSpecs;
  }
}
