package healthtech.sandbox;

/*Generated by MPS */


public class LimitedRange extends Range {
  private Float operand;
  private Float secondOperand;

  public Float getOperand() {
    return this.operand;
  }
  public void setOperand(Float operand) {
    this.operand = operand;
  }
  public Float getSecondOperand() {
    return this.secondOperand;
  }
  public void setSecondOperand(Float secondOperand) {
    this.secondOperand = secondOperand;
  }

  @Override
  public boolean checkRange(Measurement m) {
    boolean res = false;
    Float value = (getType() == MType.DIASTOLIC ? MeasurementUtils.getDiastolic(m) : (getType() == MType.SYSTOLIC ? MeasurementUtils.getSystolic(m) : Float.valueOf(m.getValue())));
    if (getOperator().equals("-")) {
      return value <= secondOperand && value >= operand;
    }
    return res;
  }
}
