package healthtech.sandbox;

/*Generated by MPS */

import java.time.LocalDateTime;

public class Measurement {
  private String uid;
  private MType type;
  private LocalDateTime created;
  private String value;
  private MUnit unit;

  public String getUid() {
    return this.uid;
  }
  public void setUid(String uid) {
    this.uid = uid;
  }
  public MType getType() {
    return this.type;
  }
  public void setType(MType type) {
    this.type = type;
  }
  public LocalDateTime getCreated() {
    return this.created;
  }
  public void setCreated(LocalDateTime created) {
    this.created = created;
  }
  public String getValue() {
    return this.value;
  }
  public void setValue(String value) {
    this.value = value;
  }
  public MUnit getUnit() {
    return this.unit;
  }
  public void setUnit(MUnit unit) {
    this.unit = unit;
  }
}
