package healthtech.sandbox;

/*Generated by MPS */


public class MeasurementUtils {

  private MeasurementUtils() {
  }
  public static Float getDiastolic(Measurement m) {
    String diatolic = m.getValue().substring(m.getValue().indexOf("/"));
    return Float.valueOf(diatolic);
  }
  public static Float getSystolic(Measurement m) {
    String systolic = m.getValue().substring(0, m.getValue().indexOf("/"));
    return Float.valueOf(systolic);
  }

}
