package healthtech.sandbox;

/*Generated by MPS */


public enum MUnit {
  KILOGRAM("kg"),
  CELSIUS_DEGREES("°C"),
  BEATS_PER_MINUTE("bpm"),
  MERCURY_MM("mmHG"),
  MOL_PER_LITRE("mmol/L");

  private String unit;

  MUnit(String unit) {
    this.unit = unit;
  }

  public String getUnit() {
    return this.unit;
  }
}
