package healthtech.sandbox;

/*Generated by MPS */


public class OutputResult {
  private String description;

  public String getDescription() {
    return this.description;
  }
  public void setDescription(String description) {
    this.description = description;
  }
}
