package healthtech.sandbox;

/*Generated by MPS */


public class OutputResult {
  private String description;
  private OutputStatus status;
  private String reminder;
  private String protocol;

  public String getDescription() {
    return this.description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  public OutputStatus getStatus() {
    return this.status;
  }
  public void setStatus(OutputStatus status) {
    this.status = status;
  }


  public String getReminder() {
    return this.reminder;
  }
  public void setReminder(String reminder) {
    this.reminder = reminder;
  }


  public String getProtocol() {
    return this.protocol;
  }
  public void setProtocol(String protocol) {
    this.protocol = protocol;
  }
}
