package healthtech.sandbox;

/*Generated by MPS */


public abstract class Range {
  private MType type;
  private String operator;

  public MType getType() {
    return this.type;
  }
  public void setType(MType type) {
    this.type = type;
  }
  public String getOperator() {
    return this.operator;
  }
  public void setOperator(String operator) {
    this.operator = operator;
  }
}
