package healthtech.sandbox;

/*Generated by MPS */


public class UnaryRange extends Range {
  private Float operand;


  public Float getOperand() {
    return this.operand;
  }
  public void setOperand(Float operand) {
    this.operand = operand;
  }
}
