package healthtech.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBehaviorAspectDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.BHDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public final class BehaviorAspectDescriptor extends BaseBehaviorAspectDescriptor {
  private final BHDescriptor myTemperatureMeasurement__BehaviorDescriptor = new TemperatureMeasurement__BehaviorDescriptor();
  private final BHDescriptor myPulseMeasurement__BehaviorDescriptor = new PulseMeasurement__BehaviorDescriptor();
  private final BHDescriptor myGlucoseMeasurement__BehaviorDescriptor = new GlucoseMeasurement__BehaviorDescriptor();
  private final BHDescriptor myMeasurement__BehaviorDescriptor = new Measurement__BehaviorDescriptor();
  private final BHDescriptor myWeightMeasurement__BehaviorDescriptor = new WeightMeasurement__BehaviorDescriptor();
  private final BHDescriptor myBloodPressureMeasurement__BehaviorDescriptor = new BloodPressureMeasurement__BehaviorDescriptor();
  private final BHDescriptor myDiastolicPressueMeasurement__BehaviorDescriptor = new DiastolicPressueMeasurement__BehaviorDescriptor();
  private final BHDescriptor mySystolicPressureMeasurement__BehaviorDescriptor = new SystolicPressureMeasurement__BehaviorDescriptor();
  private final BHDescriptor myProtocol__BehaviorDescriptor = new Protocol__BehaviorDescriptor();

  public BehaviorAspectDescriptor() {
  }

  @Nullable
  public BHDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return myBloodPressureMeasurement__BehaviorDescriptor;
      case 1:
        return myDiastolicPressueMeasurement__BehaviorDescriptor;
      case 2:
        return myGlucoseMeasurement__BehaviorDescriptor;
      case 3:
        return myMeasurement__BehaviorDescriptor;
      case 4:
        return myProtocol__BehaviorDescriptor;
      case 5:
        return myPulseMeasurement__BehaviorDescriptor;
      case 6:
        return mySystolicPressureMeasurement__BehaviorDescriptor;
      case 7:
        return myTemperatureMeasurement__BehaviorDescriptor;
      case 8:
        return myWeightMeasurement__BehaviorDescriptor;
      default:
    }
    return null;
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x302f6a2f71494d75L, 0x8daf01fecbeaf5d3L, 0x3d41ce506dda978dL), MetaIdFactory.conceptId(0x302f6a2f71494d75L, 0x8daf01fecbeaf5d3L, 0x3d41ce506dda9794L), MetaIdFactory.conceptId(0x302f6a2f71494d75L, 0x8daf01fecbeaf5d3L, 0x1f38b4c7398f1c67L), MetaIdFactory.conceptId(0x302f6a2f71494d75L, 0x8daf01fecbeaf5d3L, 0x3d41ce506dda9788L), MetaIdFactory.conceptId(0x302f6a2f71494d75L, 0x8daf01fecbeaf5d3L, 0x41ac8d399bc1bfe2L), MetaIdFactory.conceptId(0x302f6a2f71494d75L, 0x8daf01fecbeaf5d3L, 0xbb4c0906e476e7L), MetaIdFactory.conceptId(0x302f6a2f71494d75L, 0x8daf01fecbeaf5d3L, 0x3d41ce506dda9795L), MetaIdFactory.conceptId(0x302f6a2f71494d75L, 0x8daf01fecbeaf5d3L, 0xbb4c0906e39f51L), MetaIdFactory.conceptId(0x302f6a2f71494d75L, 0x8daf01fecbeaf5d3L, 0x3d41ce506dda9789L)).seal();
}
