package com.boyarsky.lang.runtime;

/*Generated by MPS */

import java.util.List;
import com.boyarsky.lang.runtime.impl.OutputResult;
import com.boyarsky.lang.runtime.impl.Measurement;

public interface IProtocol {
  List<OutputResult> evaluate(List<Measurement> measurments);
}
