package com.boyarsky.lang.runtime;

/*Generated by MPS */

import com.boyarsky.lang.runtime.impl.MType;
import com.boyarsky.lang.runtime.impl.Measurement;

public abstract class Range {
  private MType type;
  private String operator;

  public MType getType() {
    return this.type;
  }
  public void setType(MType type) {
    this.type = type;
  }
  public String getOperator() {
    return this.operator;
  }
  public void setOperator(String operator) {
    this.operator = operator;
  }

  public abstract boolean checkRange(Measurement m);
}
